### ISSUE TITLE
Future/Stream based SSH

### ISSUE THREAD

**Issue by davystrong** [GreenAppers/dartssh#5]
Is there any way to use this library using futures and streams? The actual SSHClient class seems to be based on callbacks. Is this possible?

**Comment by GreenAppers** [comment]
Would this work?

```
var controller = StreamController<String>();
SSHClient sshClient = SSHClient(
  ...,
  response: (_, v) => controller.add(v),
  disconnected: () => controller.close(),
);
return controller.stream;
```

Adding some helpers, and/or tests would be good.

**Comment by davystrong** [comment]
Thanks for your quick response! Yes, I know that can be done, and I could just read each string and decide if the terminal is ready. I would like to watch something like ```Future<bool> SSHClient.ready``` to see when the login is complete and the system is ready to receive input, however this may not even be something SSH is capable of.

**Comment by GreenAppers** [comment]
Input can be sent (or tunneled connections opened) after the `success` callback, e.g. https://github.com/GreenAppers/dartssh/blob/master/example/dartssh.dart#L114

**Comment by davystrong** [comment]
Ah, ok. That's perfect. Sorry for what probably should have been obvious, but I got a bit confused with all the options! Thank you for your help!
