### ISSUE TITLE
Duplicated root@xxx1234:~$ line

### ISSUE THREAD

**Issue by jkoenig134** [GreenAppers/dartssh#6]
I know, that this is not a problem with your implementation, but how is it possible to remove those duplicated lines? 

If i execute ls the command `ls -a` the client outputs
```
ls -a
.  ..  .bash_history  .bash_logout  .bashrc  .gnupg  .profile
root@xxx1234:~$
root@xxx1234:~$
```
so it duplicates the given input and the `root@xxx1234:~$` line.

Do you know why this happens and how to fix it?

Btw, thanks for that awesome library!

**Comment by GreenAppers** [comment]
That might be a terminal emulation issue.  Make sure that you're supplying `termvar` to the `SSHClient` constructor.

Is your use case interactive? (e.g. sending the SSH channel data to another terminal emulator).  If so, setting `termvar` to `xterm` would be good place to start.

On the other hand if you're, e.g. doing some remote scripting, you'd probably want to set `termvar` to `dumb` and possibly run some `stty` commands at the start of the session. bash regularly redraws the prompt using escape codes for interactive terminals.

If you're making an SSH mobile app, you'll probably want a terminal emulator for Dart.  I'm not sure of the existing options there.  That might be a future project I'd consider.  

Cheers!

**Comment by jkoenig134** [comment]
Thanks for the Fast answer! You are right, i want to make an ssh terminal emulator. Why is your library not good for it?
And.. How can i set the termvar?

**Comment by jkoenig134** [comment]
@GreenAppers I found the termvar variable in the SSHClient constructor. But it doesn´t take effect.

**Comment by GreenAppers** [comment]
A terminal emulator transduces a byte stream into a series of pixel buffers.

The termvar is probably taking effect, but it will only change the resulting byte stream.  It can't render the byte stream into a screen, e.g. by interpreting escape codes as cursor movements.

It looks like there are at least some terminal emulator packages for Dart.  I haven't tried any of them.

If I created a terminal emulator it would be a separate package, probably named dartterm.  The interface would accept as input the SSH channel data, and produce as output a Canvas or Widget.  I do have some old C++ code for a terminal emulator (just as I had old C++ code for SSH transport).  I'll look into this in future, but ATM I'm busy with other work. Thanks!

**Comment by jkoenig134** [comment]
At the moment i just wanted to send and receive text. The design for the ssh client is another part. The command `stty -echo` worked for me. Nothing gets duplicated.
