### ISSUE TITLE
Execute commands and download files

### ISSUE THREAD

**Issue by postacik** [GreenAppers/dartssh#7]
Hi,
This is not an issue but a feature/help request.

Your sample app (dartssh.dart) is a good example of a terminal ssh client but what I need is to connect to a server, execute commands and take actions depending on the exit codes of those commands.

I also need to download/upload files like the scp command does.

https://en.wikipedia.org/wiki/Secure_copy_protocol

I can execute commands using the `sendChannelData` function and receive the command output but I could not figure out how can I get the exit code of the command.

I think the scp command uses "cat <filename>" command under the hood and writes the output to the specified file name. Can this action be simulated using this library?

**Comment by wholenews** [comment]
The exit status is not currently returned.

At https://github.com/GreenAppers/dartssh/blob/master/lib/protocol.dart#L1043
would need something like `if (requestType == "exit-status") { width = input.getUint32(); }` (or add a new variable)

Then at https://github.com/GreenAppers/dartssh/blob/master/lib/client.dart#L413 plumb the result back up.

**Comment by postacik** [comment]
Thank you very much for the reply.

Can you please elaborate the following sentence? How can I plumb the `width` variable back up?

_Then at https://github.com/GreenAppers/dartssh/blob/master/lib/client.dart#L413 plumb the result back up._

And is it possible to download files using this library like the scp command does?
