### ISSUE TITLE
Need a advice with ssh tunnelling 

### ISSUE THREAD

**Issue by redDwarf03** [GreenAppers/dartssh#8]
Hello

I would know if it possible to connect to a VPS directly with ssh tunnelling
In putty, I use the command

-L 9999:localhost:9009 root@IP_ADDRESS -pw PaSSWORD

Thx

**Comment by wholenews** [comment]
`dart example/dartssh.dart -l root IP_ADDRESS --tunnel localhost:9009` will connect to localhost:9009 over a tunnel through root@IP_ADDRESS. It won't bind and listen on port 9999 but you could add that code if you want.

**Comment by redDwarf03** [comment]
Thank you
I tried but I failed to add the code to listen in port 9999. Have you an idea to do this please?

**Comment by redDwarf03** [comment]
ok. that's ok for me. thank you
